In [1]:
import numpy as np

In [2]:
P = np.matrix("""-618,-824,-621
-537,-823,-458
-447,-329,318
404,-588,-901
544,-627,-890
528,-643,409
-661,-816,-575
390,-675,-793
423,-701,434
-345,-311,381
459,-707,401
-485,-357,347""").reshape((-1,3))

In [3]:
Q = np.matrix("""686 422 578 
605 423 415 
515 917 -361
-336 658 858 
-476 619 847 
-460 603 -452
729 430 532 
-322 571 750 
-355 545 -477
413 935 -424
-391 539 -444
553 889 -390""").reshape((-1,3))

In [4]:
def center(M):
    c = np.mean(M, axis=0)
    return M-c, c

In [5]:
cP, centroidP = center(P)
cQ, centroidQ = center(Q)
print(cP)
print(cQ)

[[-589.25       -207.25       -458.66666667]
 [-508.25       -206.25       -295.66666667]
 [-418.25        287.75        480.33333333]
 [ 432.75         28.75       -738.66666667]
 [ 572.75        -10.25       -727.66666667]
 [ 556.75        -26.25        571.33333333]
 [-632.25       -199.25       -412.66666667]
 [ 418.75        -58.25       -630.66666667]
 [ 451.75        -84.25        596.33333333]
 [-316.25        305.75        543.33333333]
 [ 487.75        -90.25        563.33333333]
 [-456.25        259.75        509.33333333]]
[[ 589.25       -207.25        458.66666667]
 [ 508.25       -206.25        295.66666667]
 [ 418.25        287.75       -480.33333333]
 [-432.75         28.75        738.66666667]
 [-572.75        -10.25        727.66666667]
 [-556.75        -26.25       -571.33333333]
 [ 632.25       -199.25        412.66666667]
 [-418.75        -58.25        630.66666667]
 [-451.75        -84.25       -596.33333333]
 [ 316.25        305.75       -543.33333333]
 [-487.75

In [7]:
H = cQ.T*cP
U, S, Vt = np.linalg.svd(H)
R = Vt.T * U.T
if 0>(d:=np.sign(np.linalg.det(R))):
    I = np.eye(3)
    I[-1,-1] = d
    R = Vt.T * I * U.T
    
t = -R*centroidP.T + centroidQ.T
R

matrix([[-1.00000000e+00, -2.27744073e-17, -5.73564209e-17],
        [ 1.63758187e-17,  1.00000000e+00,  4.46361394e-18],
        [ 4.14532894e-17, -1.80948110e-16, -1.00000000e+00]])

In [8]:
np.sort(cP*R+centroidQ, axis=0)

matrix([[-476.,  422., -477.],
        [-460.,  423., -452.],
        [-391.,  430., -444.],
        [-355.,  539., -424.],
        [-336.,  545., -390.],
        [-322.,  571., -361.],
        [ 413.,  603.,  415.],
        [ 515.,  619.,  532.],
        [ 553.,  658.,  578.],
        [ 605.,  889.,  750.],
        [ 686.,  917.,  847.],
        [ 729.,  935.,  858.]])

In [9]:
np.sort(Q, axis=0)

matrix([[-476,  422, -477],
        [-460,  423, -452],
        [-391,  430, -444],
        [-355,  539, -424],
        [-336,  545, -390],
        [-322,  571, -361],
        [ 413,  603,  415],
        [ 515,  619,  532],
        [ 553,  658,  578],
        [ 605,  889,  750],
        [ 686,  917,  847],
        [ 729,  935,  858]])

In [10]:
t

matrix([[  68.],
        [1246.],
        [ -43.]])